describe.skip('handlebars helpers', ->
    # N.B.: In this file we will tests specifically that Handlebars has these capabilities.
    # We will not test if the functions run independently. See `mixins`.
    it('should add commas to a number', ->)
    it('should truncate numbers', ->)
    it('should format dates and times', ->)
    it('should describe the time since an event', ->)
    it('should lowercase a string', ->)
    it('should uppercase a string', ->)
    it('should capitalize the first letter of a string', ->)
    it('should titlecase a string', ->)
    it('should sentencecase a string', ->)
    it('should truncate a string', ->)
    it('should parse markdown within HTML', ->)
    it('should do something on any array element being true', ->)
    it('should get elements on the right side of an array', ->)
    it('should do something with elements on the right side of an array', ->)
    it('should get elements on the left side of an array', ->)
    it('should do something with elements on the left side of an array', ->)
    it('should get the first element of an array', ->)
    it('should do something with the first element of an array', ->)
    it('should get the last element of an array', ->)
    it('should do something with the last element of an array', ->)
    it('should join an array into a string', ->)
    it('should join an array into a sentence string', ->)
    it('should compute the array length', ->)
    it('should do something if an array is empty', ->)
    it('should do something if an array contains a specified element', ->)
    it('should iterate over an array and provide indexes', ->)
    it('should do something if two values are both true', ->)
    it('should do something if either of two values are true', ->)
    it('should do something if two values are equal', ->)
    it('should do something if two values are not equal', ->)
    it('should do something if one value is greater than another', ->)
    it('should do something if one value is less than another', ->)
)
