describe.skip('mixins module', ->
    it('should format data from an HTML form', ->)
    it('should parse a JSON file, and not error if not JSON', ->)
    it('should detect login', ->)
    it('should parse an Ajax error', ->)
    it('should validate email addresses', ->)
    it('should validate field data', ->)
    it('should validate fields from model data', ->)
    it('should capitalize the first letter of a string', ->)
    it('should underscorize a name', ->)
)
