# This is for Google App Engine ... the docs directory

application: sagefyorg
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /docs/static
  static_dir: docs/static

- url: /.*
  script: docs.index.app

libraries:

- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

- name: markupsafe
  version: "0.15"