Sagefy = require('./modules/sagefy')

document.addEventListener('DOMContentLoaded', ->
    app = new Sagefy(
        require('./adapters/signup')
        require('./adapters/login')
        require('./adapters/logout')
        require('./adapters/password')
        require('./adapters/styleguide')
        require('./adapters/terms')
        require('./adapters/contact')
        require('./adapters/settings')
        require('./adapters/dashboard')
        require('./adapters/index')
        require('./adapters/error')
        require('./adapters/search')
        require('./adapters/topic')
        require('./adapters/card')
        require('./adapters/unit')
        require('./adapters/set')
        require('./adapters/follows')
        require('./adapters/my_sets')
        require('./adapters/choose_unit')
        require('./adapters/card_learn')
    )
    app.route(window.location.pathname)
)
