const express = require('express')
const helmet = require('helmet')
const morgan = require('morgan')
const bodyParser = require('body-parser')

const errorMiddleware = require('./middleware/errorMiddleware')
const sessionMiddleware = require('./middleware/sessionMiddleware')

const indexRouter = require('./routes/index')
const sessionsRouter = require('./routes/sessions')
const usersRouter = require('./routes/users')
const userSubjectsRoute = require('./routes/userSubjects')
const noticesRouter = require('./routes/notices')
const followsRouter = require('./routes/follows')
const topicsRouter = require('./routes/topics')
const postsRouter = require('./routes/posts')
const unitsRouter = require('./routes/units')
const subjectsRouter = require('./routes/subjects')
const cardsRouter = require('./routes/cards')
const responsesRouter = require('./routes/responses')

require('express-async-errors')

const app = express()
app.use(morgan('tiny'))
app.use(helmet())
app.use(bodyParser.json())
app.use(errorMiddleware)
app.use(sessionMiddleware)

app.use('/x', indexRouter)
app.use('/x/sessions', sessionsRouter)
app.use('/x/users', usersRouter)
app.use('/x/users')
app.use('/x/users/:userId/subjects', userSubjectsRoute)
app.use('/x/notices', noticesRouter)
app.use('/x/follows', followsRouter)
app.use('/x/topics', topicsRouter)
app.use('/x/topics/:topicId/posts', postsRouter)
app.use('/x/units', unitsRouter)
app.use('/x/subjects', subjectsRouter)
app.use('/x/cards', cardsRouter)
app.use('/x/response', responsesRouter)

/* eslint-disable no-console */
app.listen(8654, () => console.log('Listening on port 8654.'))
/* eslint-enable */
