require('./page')

require('./index_')
require('./contact')
require('./error')
require('./login')
require('./logout')
require('./password')
require('./settings')
require('./signup')
require('./styleguide')
require('./terms')
