/* eslint-disable global-require, max-statements */

module.exports = function addAllEvents(store, broker) {
  require('../views/index.vnt')(store, broker)
  require('../views/components/follow_button.vnt')(store, broker)
  require('../views/components/form_field_list.vnt')(store, broker)
  require('../views/components/form_field_entities.vnt')(store, broker)
  require('../views/components/form_field_select.vnt')(store, broker)
  require('../views/components/menu.vnt')(store, broker)
  require('../views/components/notice.vnt')(store, broker)
  require('../views/components/notices.vnt')(store, broker)
  require('../views/components/post.vnt')(store, broker)
  require('../views/pages/card_learn.vnt')(store, broker)
  require('../views/pages/card.vnt')(store, broker)
  require('../views/pages/choose_unit.vnt')(store, broker)
  require('../views/pages/error.vnt')(store, broker)
  require('../views/pages/follows.vnt')(store, broker)
  require('../views/pages/log_in.vnt')(store, broker)
  require('../views/pages/my_subjects.vnt')(store, broker)
  require('../views/pages/password.vnt')(store, broker)
  require('../views/pages/post_form.vnt')(store, broker)
  require('../views/pages/search.vnt')(store, broker)
  require('../views/pages/subject.vnt')(store, broker)
  require('../views/pages/settings.vnt')(store, broker)
  require('../views/pages/sign_up.vnt')(store, broker)
  require('../views/pages/topic_form.vnt')(store, broker)
  require('../views/pages/topic.vnt')(store, broker)
  require('../views/pages/tree.vnt')(store, broker)
  require('../views/pages/unit.vnt')(store, broker)
  require('../views/pages/create.vnt')(store, broker)
}
