# TODO outline tests
require('./page')
require('./menu')

require('./home')
require('./contact')
require('./error')
require('./log_in')
require('./log_out')
require('./password')
require('./settings')
require('./sign_up')
require('./styleguide')
require('./terms')

require('./search')
require('./topic_form')
require('./post_form')
require('./topic')
require('./card')
require('./unit')
require('./set')
require('./follows')

require('./my_sets')
require('./choose_unit')
require('./card_learn')
